[package]
name = "advent-of-code-2022"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day01"
path = "src/bin/day01/main.rs"

[[bin]]
name = "day02"
path = "src/bin/day02/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
